apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps
  namespace: helm-stag-flux-ns
spec:
  interval: 10m0s
  dependsOn:
    - name: infra-configs
  sourceRef:
    kind: GitRepository
    name: helm-stag-flux-ns
  path: ./apps/staging
  prune: true
  wait: true
  timeout: 5m0s
